# pull official base image
FROM node:lts-slim

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install
RUN npm install react-scripts@5.0.0 -g

# start app
CMD ["npm", "run", "dev"]